### ISSUE TITLE
De Wiki-template van Project Tech checken en integreren bij die van ons

### ISSUE THREAD

**Issue by deannabosschert** [deannabosschert/Matcher#18]
Zie https://github.com/cmda-bt/pt-course-20-21/wiki/concept

**Comment by DanielvandeVelde** [comment]
I think you've integrated the Wiki-template quite nicely.  
You can close this imho 😄

**Comment by deannabosschert** [comment]
Thanks!! I've added a few more pages last weekend/monday, will add to those later this week(end) :)

closes #18

**Comment by deannabosschert** [comment]
Thanks!! I've added a few more pages last weekend/monday, will add to those later this week(end) :)

closes #18
