### ISSUE TITLE
Split large modules into smaller ones

### ISSUE THREAD

**Issue by ReiniervanLimpt** [deannabosschert/Matcher#33]
> I would love to see the different functions in modules, can that be done?

If you mean splitting up the authController file into smaller chunks i can agree with that, i think the current structure is fine as it is but we could consider splitting up the authController file intro 3 files being:

- everything related to a users profile, like registering and managine profiles
-  liking users and showing matches
- logging in / logging out

I think this would be the most straight forward way as i see youve made a distinction between these functions in [the router file](https://github.com/deannabosschert/Matcher/blob/main/router/index.js) already by seperating those.

Other than that, looks fine to me!

_Originally posted by @ReiniervanLimpt in https://github.com/deannabosschert/Matcher/issues/31#issuecomment-856786915_

**Comment by DanielvandeVelde** [comment]
>* everything related to a users profile, like registering and managine profiles  
>* liking users and showing matches  
>* logging in / logging out  

Yes, this was definitely something I wanted to do.  
Funny that you caught that in the router-file.  
It shouldn't be too hard to change, any of us can do it when we have the time 😄

**Comment by ReiniervanLimpt** [comment]
I can pick this up for "collaborations" sake ;)

**Comment by deannabosschert** [comment]
Haiii, this has been done :)
