### ISSUE TITLE
(A1) Job Stories schrijven

### ISSUE THREAD

**Issue by deannabosschert** [deannabosschert/Matcher#4]
You've written a good job story, there is a clear concept and there are wireframes and requirements lists

**Comment by DanielvandeVelde** [comment]
We can add my wireframes/requirements/job stories to this wiki if you want.  
That will be more than enough to close this issue.

**Comment by deannabosschert** [comment]
I've added my job stories to the individual part, and added yours to the team part.
Same with our wireframes, requirements and designs.
