### ISSUE TITLE
missing model reference

### ISSUE THREAD

**Issue by ReiniervanLimpt** [deannabosschert/Matcher#41]
# ⚙️ Issue
## 📁 Part of repo
matchController.js

## 🖊️ Issue itself
is missing: 
```javascript
const User = require("../models/user.js");
```

## 📈Recommendation
_what would you recommend (instead)?_

**Comment by deannabosschert** [comment]
![push push push](https://media4.giphy.com/media/0A477fjlRXL1n2LVgJ/giphy.gif?cid=ecf05e47w4qzxuj5wnmpwyper7hs289ixono4wljb2ntw8gq&rid=giphy.gif&ct=g)
