### ISSUE TITLE
Research soortgelijke applicaties

### ISSUE THREAD

**Issue by deannabosschert** [deannabosschert/Matcher#5]
You've researched other applications and implemented design patterns and insights in your own project

**Comment by DanielvandeVelde** [comment]
We can add my research to this wiki if you want?  
That'll take care of a big part of the research.

**Comment by deannabosschert** [comment]
> We can add my research to this wiki if you want?
> That'll take care of a big part of the research.

Yes please!
I've added mine now as well :)
